### ISSUE TITLE
Toggling scene.shadowsEnabled causes CustomMaterial to turn black

### ISSUE THREAD

**Issue by zhutq** [BabylonJS/Extensions#123]
Playground:
https://www.babylonjs-playground.com/#TVPTC8#1
Either true to false or false to true causes the problem. Default material does not have this issue.

**Comment by NasimiAsl** [comment]
i check it tomorrow sorry i see it now

**Comment by NasimiAsl** [comment]
https://www.babylonjs-playground.com/#TVPTC8#2

as you see this is not shadow problem
after you enableShadow change material.effect.setUniform is not work and  maybe 
others can explain what happen because i don't know about default material mechanism

**Comment by zhutq** [comment]
https://www.babylonjs-playground.com/#TVPTC8#3
Even without `setUniform` the ground turns black after `enableShadow` changes.
So I guess maybe there's something wrong with the uniform buffer of the material..?
May I ask @deltakosh for some help?

**Comment by NasimiAsl** [comment]
https://www.babylonjs-playground.com/#TVPTC8#4
