### ISSUE TITLE
Amp360Video - how to check if video is 360 or non-360

### ISSUE THREAD

**Issue by itorian** [BabylonJS/Extensions#158]
This plugin applies to all azure media service videos, so non-360 videos started looking horrible. We need to deliver 360 as well as non-360 videos, so how do I identify incoming video is 360 or non-360?

**Comment by sebavan** [comment]
Hello, unfortunately there is nothing the plugin can do for this. It does not have access to the video content   and even reading the video frame would be highly challenging to determine wether or not the video is a 360 one.

Could you not enable the plugin only if the video you are trying to play is 360 ? the person uploading the video should be able to provide the info ?

**Comment by itorian** [comment]
The person uploading the video can do this too but let's learn from others, like I never told YouTube that this is a 360 video, they automatically detect it and render player to play 360 and non-360 content. I will try few more today and update here.

**Comment by sebavan** [comment]
I wonder if it is not rather done server side during the video processing as it sometimes takes a bit of time to be available as 360 ? Question would then be is it easily achievable fast enough in javascript ?

I am more than happy to add some simple tool to detect it if you are aware of any cause I am not sure how efficient and reliable it would be to automate in the browser on low end devices.

**Comment by itorian** [comment]
Just noticed Google has created a tool which takes 360 mp4 file and inject 360 related metadata to it. After that we upload this 360 video on YouTube and they recognize it as 360 and attach 360 player.

Tool: https://github.com/google/spatial-media/releases/tag/v2.0
Demo: https://www.youtube.com/watch?v=D13e5VvYUQ4

How this will fit into Amp360Video, rather than asking user about it?

**Comment by sebavan** [comment]
It still does not change that the user who uploaded the video made a special action to define that it is 360. so having it in the metadata is better but not ideal as it is not an official standard (agree it is probably the most frequent one).

I could easily add a way to turn on off the plugin on demand and then it would be consumer's responsibility to take the information from where they store it (metadata, server side, client side) ?

**Comment by itorian** [comment]
Hmm, make sense. Facebook also uses same metadata injector tool for their 360 playback, ref. https://www.youtube.com/watch?v=REJaSecXdZg

Think, this way YouTube/Facebook didn't updated their apps to ask this from user's input, but updated their service to identity it reading metadata, off-course user has added that metadata.

I think this is becoming standards, so I still advocate to build/update Amp360Video plugin or azure media service or amp to read and understand that metadata. This process will not require consumer's app update to ask this from user's input, all they need is to add metadata to video if they think it is 360.

**Comment by sebavan** [comment]
This would be amazing if Azure Media Service was providing the metadata to the player as it would solve the biggest chunk of the issue.

Let me try to contact the team there to see if something is doable.

**Comment by itorian** [comment]
You can refer this feature request by me in back 2016 https://feedback.azure.com/forums/169396-azure-media-services/suggestions/11682312-360-degree-video-playback-support-on-azure-media-p

**Comment by itorian** [comment]
No problem @sebavan

**Comment by sebavan** [comment]
Still under discussion internally, not something I can fix on my side. Thanks again for your understanding and sorry for the huge wait.

**Comment by sebavan** [comment]
So I am closing the issue as it is not a client one we can develop or fix on the Babylon side. I still keep you updated in this thread if anything was moving server side. The current status is still under discussion internally in the relevant teams.

**Comment by sebavan** [comment]
And please stay ensured that I will integrate it in the client the day the info has been made available :-)
