### ISSUE TITLE
Problem with Flush Skin to show glass icon

### ISSUE THREAD

**Issue by alvesea** [BabylonJS/Extensions#159]
Hi, we have used flush skin in our player. 
We integrated with your plugin, and we observed problems in your style to show the glasses icon. 
We changed our player to use default skin and the icon appears.
Could you verify? 
Thank you, 
Edson.

**Comment by deltakosh** [comment]
is that for the Unity exporter? Pinging @MackeyK24

**Comment by MackeyK24** [comment]
I’m sorry dunno what is Flush Skin.

Can you make a quick video showing me what the issue is
