### ISSUE TITLE
ScreenSpace Canvas and WorldSpace Canvas demo error

### ISSUE THREAD

**Issue by robbisy** [BabylonJS/Extensions#160]
There's error on screenspace demo : https://www.babylonjs-playground.com/#272WI1#6
https://www.babylonjs-playground.com/#1BKDEO#22
https://www.babylonjs-playground.com/#1KYG17#1
BABYLON.ScreenSpaceCanvas2D is not a constructor
the  documentation link is broken https://doc.babylonjs.com/extensions/Canvas2D_Home
https://doc.babylonjs.com/classes/

**Comment by deltakosh** [comment]
Yes unfortunately the author of this extension has discontinued it. I would recommend using https://doc.babylonjs.com/how_to/
