### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by ArrayKnight** [BabylonJS/Extensions#172]
I'm specifically interested in seeing the ClonerSystem published to `@babylonjs/extensions/ClonerSystem` && `babylonjs-extension-cloner-system` (preferably the first, if I had to pick one)

Though the Typescript `.d.ts` file should exclude the `Demoscene` class and should extend the `BABYLON` module, not create a new module (`BABYLONX`).

It would probably be good to add a `package.json` that defines `@babylonjs/core` as a (peer?) dependency at a specific version.

Ideally, all of the extensions would be published in this manner.

**Comment by deltakosh** [comment]
Extensions are not supported by Babylonjs team directly. You need to ping the ClonerSystem author :)
