### ISSUE TITLE
npm support?

### ISSUE THREAD

**Issue by hiteshsahu** [BabylonJS/Extensions#197]
any plan to export this package as npm module to use with react es6?

**Comment by briantbutton** [comment]
The npm package is here:  https://www.npmjs.com/package/meshwriter

**Comment by hiteshsahu** [comment]
Mesh writer is for text. I need to import Dynamic Terrain. 8 couldn't find any npm package  for it.

**Comment by RaananW** [comment]
Any developer who wants to publish the package to npm can do that. We won't publish it as part of the babylon eco-system for the time being.
