### ISSUE TITLE
Example playground links error

### ISSUE THREAD

**Issue by Yonet** [BabylonJS/Extensions#202]
Links that doesn't render:
● Helvetica Neue playground example:  https://www.babylonjs-playground.com/#PL752W#53
● Comic playground example:  https://www.babylonjs-playground.com/#PL752W#52

Error message: jquery.min.js:4 GET https://sanfrancisco.ca.illuminated.city/js/meshwriter.min.js net::ERR_CERT_DATE_INVALID
![berror1](https://user-images.githubusercontent.com/3523671/87368775-7549db80-c533-11ea-8720-11c134dc11b1.png)

**Comment by RaananW** [comment]
Closing - 4 years old.
