### ISSUE TITLE
\n not working

### ISSUE THREAD

**Issue by raymondvanmil** [BabylonJS/Extensions#215]
Is everything always supposed to be on one line? I can't get \n to work

menuWORK = new Writer("line1\nline2", {"letter-height": 0.5, "anchor": "left", "letter-thickness" : 0.01, "color": "#a4494f", "colors" : {"diffuse": "#a4494f", "specular": "#a4494f", "ambient": "#a4494f", "emissive": "#a4494f"}});

**Comment by deltakosh** [comment]
Hey I recommend asking the question on the forum where the Mesh Writer creator is :)

**Comment by raymondvanmil** [comment]
hi! 'the forum' which forum is that??

**Comment by deltakosh** [comment]
Forum.babylonjs.com
