### ISSUE TITLE
 error  in ./node_modules/babylonjs-viewer/viewer/viewerManager.js  Module not found: Error: Can't resolve 'babylonjs/Misc/observable' in '/Users/My/Desktop/MyProject/node_modules/babylonjs-viewer/viewer'

### ISSUE THREAD

**Issue by JLTG2020** [BabylonJS/Extensions#221]
When I use the babylonjs-viewer,I get this error:

 error  in ./node_modules/babylonjs-viewer/viewer/viewerManager.js
Module not found: Error: Can't resolve 'babylonjs/Misc/observable' in '/Users/aleiji/Desktop/MyProject/node_modules/babylonjs-viewer/viewer'

I am sure I set types: ["babylonjs"] in tsconfig.json.And I execute the command ”yarn add babylonjs-viewer“

**Comment by JLTG2020** [comment]
> When I use the babylonjs-viewer,I get this error:
> 
> error in ./node_modules/babylonjs-viewer/viewer/viewerManager.js
> Module not found: Error: Can't resolve 'babylonjs/Misc/observable' in '/Users/aleiji/Desktop/MyProject/node_modules/babylonjs-viewer/viewer'
> 
> I am sure I set types: ["babylonjs"] in tsconfig.json.And I execute the command ”yarn add babylonjs-viewer“

**Comment by deltakosh** [comment]
Please use our forum for question: forum.babylonjs.com
