### ISSUE TITLE
TextureCanvas examples do not work in 5.0.0

### ISSUE THREAD

**Issue by andreasplesch** [BabylonJS/Extensions#227]
https://playground.babylonjs.com/#9S5YZY#6 does not seem to work for me in 5.0.0 but does in 4.2.0.

**Comment by sebavan** [comment]
@Poolminer, The _texture of rendertarget has changed in latest to be more webgpu friendly, would you be able to update ?

**Comment by RaananW** [comment]
Project removed from the repository, closing.
