### ISSUE TITLE
Zoom Out create a fisheye view

### ISSUE THREAD

**Issue by mikezero84** [BabylonJS/Extensions#247]
Using the last version if you use the mouse wheel scroll trying to zoom out the video rendered in 360 start to visualize it like fisheye, how this could be limited or fixed to avoid this?.

example:
https://drive.google.com/file/d/1jI8Dc5e_sDW9sDjYdTa3WHCF4y1347Sp/view?usp=sharing

**Comment by sebavan** [comment]
@RaananW might have an idea ?

**Comment by RaananW** [comment]
Would be great to discuss that in the forum. In general, setting a max radius to the camera will solve this, but seeing the playground or some code will be more helpful. Ping me in the forum.

**Comment by mikezero84** [comment]
Sure, @RaananW  could you share me the link of the forum? to continue discussing this issue.

**Comment by mikezero84** [comment]
done @RaananW 
https://forum.babylonjs.com/t/amp360video-zoom-out-create-a-fisheye-view/37764

**Comment by RaananW** [comment]
Sorry, didn't understand that this is related to the amp360 plugin. Will be fixed shortly

**Comment by mikezero84** [comment]
Hi I downloaded the last version of the library amp-360video.js and I got now an error
https://raw.githubusercontent.com/BabylonJS/Extensions/master/Amp360Video/dist/amp-360video.js
        
    Uncaught TypeError: h.createExternalTexture is not a function
    at new xi (amp-360video.js:formatted:18584:112)
    at In._initTexture (amp-360video.js:formatted:28033:25)
    at new Sn (amp-360video.js:formatted:27893:32)
    at new In (amp-360video.js:formatted:28016:9)
    at amp-360video.js:formatted:54871:32
    at b.<anonymous> (amp-360video.js:formatted:54896:18)
    at e (azuremediaplayer.min.js:46:29013)



`<video id="azuremediaplayer" class="azuremediaplayer amp-default-skin amp-big-play-centered" tabindex="0" width="100%" height="100%"> </video>

            var myOptions = {
                nativeControlsForTouch: false,
                heuristicProfile: "HighQuality",
                autoplay: false,
                controls: true,
                width: "100%",
                height: "100%",
                poster: "",
                logo: { "enabled": false },
                techOrder: ["azureHtml5JS", "html5"],
                plugins: {
                    "threeSixty": {
                        enableVR: true
                    },
                    "zoom": {} 
                }
            };

            var myPlayer = amp('azuremediaplayer', myOptions, function () {
                console.log('Good to go!');
                // add an event listener
                this.addEventListener('ended', function () {
                    console.log('Finished!');
                });
            });
            
            myPlayer.src([{
                src: "video_url",
                type: "application/vnd.ms-sstr+xml"
            }]);


`

**Comment by RaananW** [comment]
Should be good now. there was a missing extension in production

**Comment by mikezero84** [comment]
no worries it happens sometimes
