### ISSUE TITLE
HtmlMesh base size is not calculated correctly if the camera is not aligned with z

### ISSUE THREAD

**Issue by ericwood73** [BabylonJS/Extensions#261]
https://www.babylonjs-playground.com/#Y2LIXI#28

**Comment by CTOSPACE** [comment]
Yes, I don't have a good understanding of Matrix, even though I studied it in college, so I can't handle this problem. If possible, I hope you can handle it, and then I will merge it into my PR. I will make the modifications according to your suggestions, and then restart to initiate PR. Is this okay? My reply is from the translation software, and I hope there won't be too much deviation in the translation

**Comment by ericwood73** [comment]
Actually, if you don't mind, go ahead and make the changes we discussed to your PR.  I'll merge and then I'll fix this, since I have a repro.
