### ISSUE TITLE
An error occurred in the size of the asynchronous creation of htmlMesh

### ISSUE THREAD

**Issue by CTOSPACE** [BabylonJS/Extensions#268]
https://www.babylonjs-playground.com/#Y2LIXI#57

When HTMLMesh is generate deferred, such as through setTimeout 2000ms, its size will be incorrect. When I debug it, a delayed generated HTMLMesh's requestUpdate is always false, and the 'this.updateBaseScaleFactor' can't be called anytime

@ericwood73

**Comment by CTOSPACE** [comment]
so, i modifited the code as bellow, i am do not sure this way is right, but it's works
<img width="537" alt="图片" src="https://github.com/BabylonJS/Extensions/assets/1892162/32e723db-572b-4d42-a6d4-8f9f26660241">

**Comment by ericwood73** [comment]
Thanks for reporting.  This has been fixed by PR #269
