### ISSUE TITLE
need to interact with camera to play YouTube video on iPhone

### ISSUE THREAD

**Issue by v3vr** [BabylonJS/Extensions#276]
Hello, 
It appears that to play YouTube video on iPhone, user needs to interact with the camera; otherwise clicking on the YouTube video is ignored

How to reproduce

Open the repo's playground https://www.babylonjs-playground.com/#Y2LIXI#44

It works as expected on a desktop.
However, on iPhone, when I click on the youtube video, nothing happens. If I slightly rotate the camera (even by one degree) and click on the video again, it starts to play. 

Note: while the video is playing, I can continue to manipulate the camera, which is GREAT!

**Comment by yuripourre** [comment]
@v3vr I just checked on my Google Pixel 7 and the YouTube video doesn't play at all. Even rotating the camera.

**Comment by sebavan** [comment]
@ericwood73 this might be a good candidate for you ?

**Comment by ericwood73** [comment]
> @v3vr I just checked on my Google Pixel 7 and the YouTube video doesn't play at all. Even rotating the camera.

I just tried on my Pixel 7 and it worked for me.  Could you try again?  Maybe it was YT?

**Comment by ericwood73** [comment]
It seems pointermove doesn't trigger on ios if the user just taps.  I added a listener for touchstart on ios and that allows the user to interact with the iframe after an initial touch.  I tried triggering the event manually, but iOS would have none of it.  Unfortunately, I think this is the best we are going to be able to do on iOS.

**Comment by yuripourre** [comment]
> > @v3vr I just checked on my Google Pixel 7 and the YouTube video doesn't play at all. Even rotating the camera.
> 
> I just tried on my Pixel 7 and it worked for me. Could you try again? Maybe it was YT?

Yep! It worked now.

**Comment by v3vr** [comment]
@ericwood73 Thank you for looking into this
