### ISSUE TITLE
Polyhedron playground error

### ISSUE THREAD

**Issue by crdev** [BabylonJS/Extensions#287]
https://github.com/BabylonJS/Extensions/tree/master/Polyhedron links to http://www.babylonjs-playground.com/frame.html#21QRSK#1, which throws the following error (on 122.0.6261.94 (Official Build) for Linux Mint (64-bit)):

> Mixed Content: The page at 'https://www.babylonjs-playground.com/frame.html#21QRSK#1' was loaded over HTTPS, but requested an insecure script 'http://jerome.bousquie.fr/BJS/polyhedrons/polyhedra.js'. This request has been blocked; the content must be served over HTTPS.

This demo is rather important as it is supposed to explain all numeric polyhedra types that can be supplied in the options to `CreatePolyhedron()` (linked from `@babylonjs/core/Meshes/Builders/polyhedronBuilder.d.ts`).

**Comment by deltakosh** [comment]
@jbousquie Hey buddy! long time no talk :) Can you host the polyhedra.js on https on your side?

**Comment by crdev** [comment]
Hey-hey! :) From what I see, https://jerome.bousquie.fr/BJS/polyhedrons/polyhedra.js is a totally valid URL, so the only change required is in the loading code:

```
var url = "http://jerome.bousquie.fr/BJS/polyhedrons/polyhedra.js";
           ^^^^
```

**Comment by deltakosh** [comment]
Wanna do a PR to fix it?

**Comment by crdev** [comment]
This reference comes from https://snippet.babylonjs.com/21QRSK/1 (the `jsonPayload` field), I sadly have no idea how to edit it. Will be glad to fix if you point me in the right direction!

**Comment by deltakosh** [comment]
oh! I see! I'll check with @RaananW to update that snippet!

Thanks again!

**Comment by RaananW** [comment]
Just making sure - all that needs to be done is to change the http to https?

**Comment by crdev** [comment]
Let me put it this way: this is the first one and there may or may not be more of those :)

**Comment by RaananW** [comment]
Let me see what I can do about it ;-)

**Comment by RaananW** [comment]
Should be fine now. CDN is still being updated so it might take a few minutes until you see the changes. Also, might require a refresh on your browser, because except for rare cases, snippets are immutable.
