### ISSUE TITLE
htmlMesh does not work with the useRightHandedSystem flag set on the scene.

### ISSUE THREAD

**Issue by LudaThomas** [BabylonJS/Extensions#290]
If the scene is set to useRightHandedSystem the transforms for the css are not calculated properly.

In this test scene https://www.babylonjs-playground.com/#Y2LIXI#159 on line 11 toggle useRightHandedSystem

**Comment by sebavan** [comment]
cc @ericwood73 the brillant mind behind Html Mesh

**Comment by deltakosh** [comment]
Please use the forum for questions
