### ISSUE TITLE
Multiple ressources not working, dead ends in documentation

### ISSUE THREAD

**Issue by Lyso95** [BabylonJS/Extensions#297]
I am reading through your documentation, must say it is frustral sometimes...

One example:
https://github.com/BabylonJS/Extensions/blob/master/SceneManager/readme.md
https://github.com/BabylonJS/UnityExporter/tree/master/Manager

there are multiple other ressources, which are going to dead ends "404 ERROR"

**Comment by PirateJC** [comment]
@Lyso95 thanks for flagging this. We'll do a cleanup of the dead ends in the docs.

cc @RaananW

**Comment by karan-anantpure** [comment]
I am trying to find out the following:
[https://github.com/BabylonJS/Extensions/blob/master/ManipulationHelpers/README.md](url)

Please point out the content of the above link.
Thanks

**Comment by RaananW** [comment]
Any extension that was not updated for the last 2 years had been removed. If you are looking for it, you can check the history of the repository or contact the implementer.

Where is this link provided?
