### ISSUE TITLE
Exporting with io_tower_of_babel.py fails "with 'charmap' codec can't encode character '\u015d' in position 8: character maps to <undefined>"

### ISSUE THREAD

**Issue by matra774** [BabylonJS/Extensions#8]
Exporting simple model form Blender fails with 

>========= Writing of javascript file started =========
>========= An error was encountered =========
>  File "C:\Users\matejt\AppData\Roaming\Blender Foundation\Blender\2.76\scripts\addons\io_tower_of_babel.py", line 411, in execute
>    if (scene.export_javaScript): self.to_script_file(False, version)
>  File "C:\Users\matejt\AppData\Roaming\Blender Foundation\Blender\2.76\scripts\addons\io_tower_of_babel.py", line 463, in to_script_file
>    file_handler.write('    var ŝ = BABYLON;\n')
>  File "D:\Blender\2.76\python\lib\encodings\cp1250.py", line 19, in encode
>    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
>ERROR:  'charmap' codec can't encode character '\u015d' in position 8: character maps to <undefined>
>========= end of processing =========

Probably, the reason is that line 463 (and also some other lines) contains unicode characters that can not be processed by OS.

I am using Bledner 2.76b on  Windows 7

**Comment by matra774** [comment]
Update: replacing ă with aa and ŝ with ss indeed sovles the problem

**Comment by Palmer-JC** [comment]
Just fixed another issue common to both exporters related to baking.  Looking at this now.  The intent was to reduce file size by changing BABYLON & BABYLON.Matrix.FromValues to single unused characters.

This runs fine in Linux, but can adjust so it works for all.  As they are variables inside the scope of the module, will change to 'B' and 'M' without danger of collision in next PR, today.

**Comment by matra774** [comment]
Thanks!
